spring:
  application:
    name: joojoo-backend

  config:
    import:
      - optional:file:.env[.properties]
      - optional:classpath:.env[.properties]

  datasource:
    url: "${DB_URL}"
    username: "${DB_NAME}"
    password: "${DB_PWD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080

cors:
  origin:
    local: ${CORS_ORIGIN_LOCAL}
    development: ${CORS_ORIGIN_DEVELOPMENT}
    production: ${CORS_ORIGIN_PRODUCTION}
